### ISSUE TITLE
GUI flashback

### ISSUE THREAD

**Issue by HuanLab** [eugenemel/maven#526] opened 2022-01-28 20:04 UTC
Hi,

I have recently used EI-MAVEN to process 5 Agilent data files which are as large as 110 MB per file, and the GUI always crashed and disappeared during the step of merging slices. Is there any workaround to avoid this issue? Thanks.

**Comment by PMSeitzer** [comment] 2022-01-28 20:23
Hi @HuanLab, thanks for your question.
We don't have any control over El-Maven - you'll have to contact Elucidata with your question:
https://elucidata.io/el-maven/#:~:text=El%2DMAVEN%20is%20an%20open,for%20exploring%20the%20experimental%20data.

You are welcome to try Maven instead of El-Maven. Latest release is here:
https://github.com/eugenemel/maven/releases/tag/8.1.28.12

**Comment by HuanLab** [comment] 2022-01-28 21:21
Thank you!. I tried using the widows version of Maven. However, I could not get any features extracted in the result. Please see attached the paramters I used in capture 1 and 2, and the resulting feature table in Capture 3. Any idea why? Something wrong with the parameters maybe? Thank you.
![Capture1](https://user-images.githubusercontent.com/52514403/151623186-4cdc18c3-a723-4f0c-99d9-2d6afdcf0908.JPG)
![Capture2](https://user-images.githubusercontent.com/52514403/151623194-b9296424-43ec-449a-9f6d-503c9320a8c1.JPG)
![Capture3](https://user-images.githubusercontent.com/52514403/151623199-40646431-1b2a-4aa1-82ab-90c89e345e7e.JPG)

**Comment by PMSeitzer** [comment] 2022-01-28 22:37
@HuanLab  Hm, not sure what the problem could be.  If you make your `mzXML` files available I can load them and try to figure out what's going on.

**Comment by HuanLab** [comment] 2022-01-28 22:42
[Demo Data.zip](https://github.com/eugenemel/maven/files/7962257/Demo.Data.zip)
@PMSeitzer Here are the zip file containing five mzXML files. Thank you.

**Comment by PMSeitzer** [comment] 2022-01-29 00:22
Hey @HuanLab, thanks for sending that over.  I was able to run the data through MAVEN, and I'm also seeing no results.
Can you provide information about specific compounds / features I should be able to see in the data?

One thing you might try would be to re-convert your raw files into mzML files using proteowizard.  Looking at the raw mzXML files, I'm wondering if perhaps they were created with an older version of proteowizard, and so MAVEN is struggling to read them properly.  In the mean time, I'll keep looking into it and see what I can discover.

One thing you can do with MAVEN right now is look at the scan-by-scan data. For instance, I was looking at the`m/z = 121.12379456`.  Maven appears to be confused about these files, and is not showing any intensity in the EIC widget, so clearly there is something wrong:

To show the `MS1 List` and `MS2 List`, navigate to the `Widget` drop-down menu.

<img width="1613" alt="scan_list_example_widget" src="https://user-images.githubusercontent.com/1757701/151638564-f0124a19-cf6a-4d66-9643-a7875a20688c.png">

**Comment by HuanLab** [comment] 2022-01-29 01:54
Hi, 

I was able to process these files using XCMS and MS-DIAL with no issues. These are five replicates from Urine LC-MS analysis in positive ionization mode and the acquisition is DDA mode. Actually EI-MAVEN can also process these files with no issues. EI-MAVEN just cannot process the Agilent data only. So I dont think the raw data is corrupted. Does Maven only support mzML format though?

**Comment by PMSeitzer** [comment] 2022-02-01 04:46
Hi @HuanLab - I think I found the problem.
In the settings, there is a parameter called "EIC Scan Filter" that it appears by default is set to "SIM".
This parameter is located in the "Peak Detection" tab of the "Options" dialog box, which you can open by clicking on the "Options" button in the main window.
Replace the "SIM" text with an empty string (just delete the text), and click the "Recompute EIC" button.  Doing so made it possible for me to see the intensity in the EIC widget.

In the future, I'll be sure to make the default setting for this parameter an empty string to avoid this confusion.

![scan_Filter_option_window](https://user-images.githubusercontent.com/1757701/151914161-f7305297-b913-46f4-957a-7584f4ee6c71.png)

**Comment by PMSeitzer** [comment] 2022-02-01 04:50
@HuanLab Here is an example with the "SIM" option removed, showing two peak groups with `m/z = 358.2560`:

![peak_group_358](https://user-images.githubusercontent.com/1757701/151914429-b04ed333-201b-4766-92ab-54a484695a05.png)

**Comment by PMSeitzer** [comment] 2022-02-01 04:56
`TODO:` Add a notification to the EIC widget when a scan filter is being applied.  This will avoid the confusion of missing scan data.

**Comment by HuanLab** [comment] 2022-02-01 22:39
@PMSeitzer Is there any chance you can give me a step-by-step protocol showing how you get the feature table from the files I sent to you? The EIC scan filter on my side is always empty.  And nothing happened when I clicked on the Recompute EIC button. Here is what I did: first I clicked on Open and import these five mzXML files; then I click on Peak button and a parameter setting window popped up. I adjusted all the parameters and then clicked on "find peaks" button at the bottom of the window. Is there anything wrong with what I did? Again, the "EIC scan filter" on my side is empty by default.

**Comment by PMSeitzer** [comment] 2022-02-01 23:34
Hi @HuanLab,
OK, I have conducted a search, and saved the results into the shared Demo.Data folder.
for this search, I chose some parameters semi-arbitrarily, the parameters I picked might not be optimal for your dataset.

I think the most important parameter is the check box 
- [x] `Retain peak groups that do not match to compounds`

should be checked, because by default, there are no compounds loaded.

Here is how I conducted the search:

(1) open MAVEN.
(2) load mzXML files.
(3) click the "peaks" button.
(4) Set settings to values as in screenshots:

![peak_detection_parameters](https://user-images.githubusercontent.com/1757701/152069302-7c91e19d-8e40-48a1-9435-89e09de4dc38.png)

![peak_scoring_parameters](https://user-images.githubusercontent.com/1757701/152069292-18c49d85-b67c-4404-87df-132ac3f35a39.png)

(5) click "Find Peaks" button at the bottom of the dialog.
(6) Save results.

**Comment by HuanLab** [comment] 2022-02-02 03:56
@PMSeitzer Thanks. It works this time. But when I loaded the thermo QE dataset with three mzXML files, I got no results generated again. Could you please help checking the data? FYI, I was able to get the results from XCMS and MSDIAL. So the data set itself should be fine.
[QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_03.zip](https://github.com/eugenemel/maven/files/7983454/QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_03.zip)
[QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_04.zip](https://github.com/eugenemel/maven/files/7983455/QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_04.zip)
[QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_05.zip](https://github.com/eugenemel/maven/files/7983456/QXA05NEG20200407_INOV010119INTR_HUMAN_FECAL_05.zip)

**Comment by PMSeitzer** [comment] 2022-02-03 00:10
Hi @HuanLab,

It appears that MAVEN is not detecting any MS2 scans in the `HUMAN_FECAL` files.

If you follow the steps I described for the last dataset, you can generate peak groups, however you do have to change one parameter: the check box
- [ ] `Must Have MS2`

must be **unchecked**.  This checkbox is located on the `Peak Detection` tab of the peaks search.

Once again, I would encourage parameter exploration / attention, as the parameters I've provided might not be suitable for this dataset.  MAVEN returns a huge number of peak groups with the default settings, so I'd recommend increasing the number of good peaks / group, minimum intensity, and consider a wider smoothing window and minimum number of scans per peak.

**Comment by PMSeitzer** [comment] 2022-02-03 00:13
@HuanLab : one more thing - to help you in exploring parameters, you can use the UI Features in MAVEN, for instance, the `Show Merged EIC` shows you the consequences of different smoothing windows, various UI options render peaks in different ways, e.g. as points, lines, or filled shapes:

![smoothing_UI_options](https://user-images.githubusercontent.com/1757701/152259235-754710f3-6db4-4422-a747-66049b7dd945.png)

Best of luck in your analysis.  I'm trying to publish a software paper soon with more descriptions of MAVEN, as the program has become quite large, with many options, and isn't all that user-friendly (At least at first).  Any suggestions/feedback you can provide would be appreciated.

**Comment by HuanLab** [comment] 2022-02-03 01:48
@PMSeitzer The odd part is I did uncheck that box but still got no groups in the result panel. Capture 1 and 2 show the parameters I used, and capture 3 shows that there is no detected features in the result panel.
![Capture1](https://user-images.githubusercontent.com/52514403/152267773-c2c11cf2-b23a-4cda-8f2c-3faf90c272bb.JPG)
![Capture2](https://user-images.githubusercontent.com/52514403/152267778-55367fa5-f174-460b-85d0-3fb4fabcd89a.JPG)
![Capture3](https://user-images.githubusercontent.com/52514403/152267779-5d9bd25b-97bf-4821-8cde-60fc5058631c.JPG)

**Comment by PMSeitzer** [comment] 2022-02-03 17:53
Hi @HuanLab,
I think the with the parameter settings you've picked, the program will generate too many peaks.  The reason the `Detected Features` table is showing empty is because the program is busy converting all of the identified peak groups into a table of results.

Here are some results I found using stricter parameters:
![peak_detection_parameters](https://user-images.githubusercontent.com/1757701/152399862-704e7a43-22c7-481f-ba2f-0b7092493c54.png)

![peak_scoring_parameters](https://user-images.githubusercontent.com/1757701/152399880-08f76a90-5476-4e3c-90cf-e0238a567d5c.png)

some results:

![fecal_example_1](https://user-images.githubusercontent.com/1757701/152399949-963b00c2-5293-4ec7-9485-da7bf4039ee8.png)

![fecal_example_2](https://user-images.githubusercontent.com/1757701/152399965-1d86d914-b925-4c02-b88b-1d91d0835b04.png)

Is there a set of compounds you are trying to identify? If so, I'd recommend you format these into a library, load the library, and do a Peaks search where you keep the option to retain peak groups that do not match to compounds unchecked.  That way, you can keep the parameters a little bit looser to avoid identifying too many peak groups.

**Comment by HuanLab** [comment] 2022-02-03 20:39
@PMSeitzer I tried using exactly the same parameters as you did, but still got nothing. The setting window just quickly disappeared after I clicked "find peaks" in less than a second. I do not think it is because the software was processing too many groups and eventually crashed. It disappeared so fast that it seemed to be something wrong with code when data like this was processed. Actaully EI-MAVEN was able to process this data but it would crash in the middle of merging groups. That was probably because EI-MAVEN was not able to handle so many groups.

**Comment by PMSeitzer** [comment] 2022-02-03 21:52
@HuanLab Hmm, that is mysterious - I'm not sure what is happening.  

Can you launch MAVEN using the debugging console, and paste the console output here, after you see the dialog disappear?

Are there any program settings that you think might be causing the issue?

Maybe there is a windows-specific bug, since I am running on mac os x and it looks like you are running in windows.  If that's the case, I would need to fix the program and put out a new release. 
Are you able to try to out the program on a non-windows operating system?

Good luck!

**Comment by HuanLab** [comment] 2022-02-03 23:30
![image](https://user-images.githubusercontent.com/52514403/152444668-b20123ec-9108-48c6-a18e-7bf77a8ca66e.png)
This is what happened after I clicked “find peaks”. I am wondering if you have any R script involved in the software. And if the R package on my computer is not compatible with your software, the window would just crash I assume? Unfortunately, I only use Windows system. It seems this is a system-specifc issue?

**Comment by PMSeitzer** [comment] 2022-02-04 01:16
Hi @HuanLab ,
Maven wouldn't be trying to execute any R scripts, so I don't think that's the problem.  Looking at the debug log, it looks like it thinks everything went well, but it couldn't find many slices, and correspondingly, couldn't find many peaks.

Comparing the debug log with the one I observe when I run the code, we can see some differences:

![debug_log](https://user-images.githubusercontent.com/1757701/152455354-eaa1b3c7-a4ad-4498-9083-50f56336949d.png)

It's worth mentioning that when you search data that has MS2 scans, and you click the "must have MS2" checkbox, MAVEN uses a different peak picking algorithm than if the "must have MS2" checkbox is checked.  When the box is unchecked, MAVEN uses `algorithmB`, when checked, MAVEN uses `algorithmE`.  It's possible that there is something subtle happening in your case that only affects `algorithmB`, but not `algorithmE`.

I'm not sure what to suggest at this point - since I can't reproduce your bug, it would be hard for me to debug it.  Perhaps you could try running MAVEN on a different computer?
At the least, it appears that things are working for data that has MS2 scans - so MAVEN can still be used for that analysis.

If it's helpful at all, here is the source code for `algorithmB`, where we are seeing differences (`algorithmB` returned 205 slices in your case, 2060 slices in my case):
https://github.com/eugenemel/maven_core/blob/master/libmaven/parallelMassSlicer.cpp#L22-L124

Feel free to take a look. If you have any more ideas or think you may see the problem, let me know and I'll be happy to fix it.

I'll give it some more thought and let you know if I think of anything else.

**Comment by HuanLab** [comment] 2022-02-04 05:35
@PMSeitzer Thank you. I will wait for your comments.

**Comment by PMSeitzer** [comment] 2022-02-09 20:22
Hey @HuanLab ,

I'm still not sure what's happening - I'd recommend trying installing/running MAVEN on a different computer.  If you do get a chance to try that, could you post the console output here?

**Comment by PMSeitzer** [comment] 2022-07-25 17:07
Hi @HuanLab,

Out of curiosity, were you ever able to get MAVEN to work?
There are some new releases since the last post on this thread.

**Closed by PMSeitzer** 2022-07-25 17:07 UTC
Labels: bug, windows
