### ISSUE TITLE
Mac OS 13.3.1 cannot load mzXML files

### ISSUE THREAD

**Issue by jessyutingtan** [eugenemel/maven#628] opened 2023-04-17 15:06 UTC
My Mac OS is Ventura 13.3.1. However, I cannot load mzXML files into Maven2 no matter which way I tried. I also downloaded Xcode to my Mac, still didn't help. This is so frustrating, looking forward to any kind advice! Thanks very much!

**Comment by PMSeitzer** [comment] 2023-04-17 16:35
Hi @jessyutingtan thanks for your interest in MAVEN.
Which release of MAVEN2 were you using?
What do you see when the mzXML files fail to load?
It's possible that the problem could be associated with the specific mzXML files - how were they generated?

Any additional information you can provide will be helpful - e.g., screenshots, data files, etc.

**Comment by jessyutingtan** [comment] 2023-04-17 19:31
Attachments available until May 17, 2023
Hi Phillip,

Thanks for reaching out. I was using Maven 2.1.0 for Mac.

Attached is a short video clip showing what looks like after loading mzXML file to it.

I’m also attaching two mzXML files - we collaborated with Dr. Josh Rabinowitz's lab at Princeton University, and the mzXML files were created by their LC/MS instrument. Let me know if you need more information. Thanks! -Jessy

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVKw4ahEuZ10GdPU-jvPfJ9Eijq8AaLrBnRtXYzX0fUMlF4AB_FUtagT%2F%24%7Bf%7D%3Fo%3DAiVHAEs8KV7MM3SmwAv4RiND7mSrKjwIp6OTOismVgnZ%26v%3D1%26x%3D3%26a%3DCAog0KFs-9niRm0GKkoB_m7exr6XL9ygmOw9M2mXy7-3n54SehCx6c2F-TAYsfnI2YIxIgEAKgkC6AMA_3lyVcpSBESKOrxaBFS1qBNqJ6AahN2JSymoAVUY6lgN79FNZey-D-wguR5O9Djb6_l7WWMReEDa7HInxLYWxcKFVoBM4bKG4BCMSTC0QTfeD7izN2viPYt9gOyOtC6nGEXA%26e%3D1684351892%26fl%3D%26r%3D8F20F158-C5A5-404C-A6E5-36016F4410A2-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DD5153D9B-5D5C-4387-A461-8A0598CC7213%26p%3D116%26s%3D__1kKIP-6qkRc3kld5YmX-_fsPU&uk=b-F99BvQPcw--MA7remtgA&f=Maven2_couldn%27t%20load%20samples%20or%20project.mov&sz=35286916>Maven2_couldn't load samples or project.mov
35.3 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FARf-rde8YtLvuAa-CZ97qSAfoniAAW_bACWEAH7B-rmtJlFyIAbMTTeN%2F%24%7Bf%7D%3Fo%3DAmrETNCB1SE-aKRSRRHT2FxZSphKvZKV72tSFmyHIumZ%26v%3D1%26x%3D3%26a%3DCAogQy4jxSQ2DQOUgUlh8TLQrhYmIiboMWweX8w42ydzsVUSehDz5M2F-TAY8_TI2YIxIgEAKgkC6AMA_0rMnodSBB-ieIBaBMxNN41qJ9gtCsE6ymGUFBbG0D-sPvkoCASlbPK36UTKrh534l2Akk2At1fkVHInerYBdxKTdukphyBGxSCQ3mf9vqTQRj0aHUARIzmDszG5mfgkw1s5%26e%3D1684351892%26fl%3D%26r%3D5610CB27-CFA6-4676-B47C-DAEC9E876DD7-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DD5153D9B-5D5C-4387-A461-8A0598CC7213%26p%3D116%26s%3DDIkT2QpVg5rLFFuU8ukHp0J0_KY&uk=Pq8U5Z1HyTfdyZfM2C9VdQ&f=Col_1.mzXML&sz=28294831>Col_1.mzXML
28.3 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FATBX6xDt6qyr87teDl3DoyxUPZOMAR5fh-cgSL_za6JGbJPDDDq1BsfR%2F%24%7Bf%7D%3Fo%3DAqvtgZQBK4twImVF287pn1pOW95-CadqNbeKKc9s4tUx%26v%3D1%26x%3D3%26a%3DCAogd4iwn8Y_6j8z__2aAmLHOW1kn5BCrrrNfp_FvNiUiagSehCS582F-TAYkvfI2YIxIgEAKgkC6AMA_y7JPJJSBFQ9k4xaBLUGx9FqJyH3E1jjlhY3tDJ0qHExZhI9VWhTXl0t_xt7gKmcyY_WOB5nOfQ0F3InYgV7Ds6L3x2CAPgFaG509Ij_pyZPPsBQpSQnNR34dgs0bWqalrX9%26e%3D1684351892%26fl%3D%26r%3D3D3C7919-2430-490F-9AF3-E6D8F6E1D2B7-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DD5153D9B-5D5C-4387-A461-8A0598CC7213%26p%3D116%26s%3D9nvrz8aWP5qNKORxIPeE3WredWM&uk=AGzCP9DlGZc8_JzsOKdgHA&f=Se1.mzXML&sz=46726838>Se1.mzXML
46.7 MB

On Apr 17, 2023, at 09:35, Phillip Seitzer ***@***.***> wrote:


Hi @jessyutingtan <https://github.com/jessyutingtan> thanks for your interest in MAVEN.
Which release of MAVEN2 were you using?
What do you see when the mzXML files fail to load?
It's possible that the problem could be associated with the specific mzXML files - how were they generated?

Any additional information you can provide will be helpful - e.g., screenshots, data files, etc.

**Comment by PMSeitzer** [comment] 2023-04-17 21:56
Thanks @jessyutingtan I was able to download the `mzXML` files, I'll have a look and let you know what I find.  For the movie, you'll have to remove the apostrophe in "couldn't" and rename the file, for the link to render properly in the ticket. So, just rename the movie file to "could not" instead of "couldn't" and try again.

**Comment by PMSeitzer** [comment] 2023-04-17 23:05
Looking at some of the JSON files I've pulled, I don't see any watcher-related fields returned - so, perhaps not

**Comment by jessyutingtan** [comment] 2023-04-18 00:03
Attachment available until May 17, 2023

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FASNizM8G-e5RnRv4T4bUHERsHiGWAfdLkBQ5TUtOJk6skY1vukmjb-_2%2F%24%7Bf%7D%3Fo%3DApNQgTtfocMNcc2pfCHfw9X7spHym-kkhEqGk9_FqCv0%26v%3D1%26x%3D3%26a%3DCAogN5uHYzVLidoXDvtOosIvKJ0vfW6E4KnZEPwxFBsZ2bkSehCSz7CN-TAYkt-r4YIxIgEAKgkC6AMA_whVVkJSBGweIZZaBKNv7_ZqJ2jWxHtBJw8fCWAAQMeRRzVmHoc2keb-8os5dZOHRMTfcSs_EYvMUXInDZnbVRFGVURHV7_7OcH-BDQriHKSoHcncdw167brNVPe1nsBXR8X%26e%3D1684368191%26fl%3D%26r%3DD73FF1D2-CE7E-466E-A159-C6EDEDA19C78-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DD5153D9B-5D5C-4387-A461-8A0598CC7213%26p%3D116%26s%3DdrV_SM2aOcyKbtW4Y01eWos4omw&uk=K180qHJ8p-tSJna3yonATg&f=Maven2_could%20not%20load%20samples%20or%20project.mov.zip&sz=34927127>Maven2_could not load samples or project.mov.zip
34.9 MB

On Apr 17, 2023, at 14:56, Phillip Seitzer ***@***.***> wrote:


Thanks @jessyutingtan <https://github.com/jessyutingtan> I was able to download the mzXML files, I'll have a look and let you know what I find. For the movie, you'll have to remove the apostrophe in "couldn't" and rename the file, for the link to render properly in the ticket. So, just rename the movie file to "could not" instead of "couldn't" and try again.

**Comment by jessyutingtan** [comment] 2023-04-18 00:05
Thanks Phillip. I just sent you the movie without apostrophe, but in zip format (somehow gmail failed to send the .mov file after trying many times).

Please let me know if you can download and open the video properly. Thanks -Jessy

On Apr 17, 2023, at 14:56, Phillip Seitzer ***@***.***> wrote:


Thanks @jessyutingtan <https://github.com/jessyutingtan> I was able to download the mzXML files, I'll have a look and let you know what I find. For the movie, you'll have to remove the apostrophe in "couldn't" and rename the file, for the link to render properly in the ticket. So, just rename the movie file to "could not" instead of "couldn't" and try again.

**Comment by PMSeitzer** [comment] 2023-04-24 17:09
Hi @jessyutingtan Thanks for the files and the movie.

Unfortunately, I was able to open the files without any problem on my system (I could not reproduce your issue).

I was wondering if you could launch MAVEN with the debugging console.  That way, when you try to open files, the program may print out some useful error information into the console.  Here is how you can do that:

You will have to update your security/privacy settings and explicitly allow MAVEN to be launched by your computer (mac os x will block the program from being launched by default. You'll need to go to `System Preferences/Security & Privacy` to make the change).

(1) right-click on the program icon and select "Show Package Contents"

![show_package_contents](https://user-images.githubusercontent.com/1757701/234067489-ba7d2dc6-016c-4e53-a242-000e32b2925f.png)

(2) navigate to a file called "Maven" located at  `Contents/MacS/Maven`

![maven_executable](https://user-images.githubusercontent.com/1757701/234067525-2c95add0-2e46-4f21-9763-80752041530c.png)


(3) launch the program. You will that a console window now launches along with the MAVEN executable.  Please carry out the process of trying to load your samples, and then copy the text in the console window and add that data to this ticket.

![window_with_console](https://user-images.githubusercontent.com/1757701/234067564-434523ff-befc-4ef3-baa0-be4ce42681e6.png)

Hope this helps, and that we'll be able to solve the problem soon.

**Comment by PMSeitzer** [comment] 2023-05-10 20:51
Hey @jessyutingtan Closing this issue for now. Update ASAP if you'd like work to continue.

**Closed by PMSeitzer** 2023-05-10 20:51 UTC
Labels: bug
