### ISSUE TITLE
Add button to lock spectra m/z axis after zooming

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#431] opened 2021-06-08 18:51 UTC
It would be helpful to quickly lock the x-axis of spectral plots to make clicking through MS2 events easier. 

There's an option to manually set the x-axis scale for these plot in Options - Spectra Display, but its currently very manual to type in values for multiple compounds/MZ ranges. Would be nice to have a button that you could click after zooming into spectral plots to lock/autozoom.

**Comment by cmsand** [comment] 2021-06-08 18:52
Added @ngoccalico in case she has thoughts. 

For DIMS - this feature would also be helpful for MS1 and MS3 plots.

**Comment by cmsand** [comment] 2021-06-08 18:58
An example of how this might be used: When peak-picking TGs, its helpful to zoom into the acyl-containing portion of the MS2 plot to match fragments against the library. By zooming in and locking the x-axis to this region you could easily click across MS2 events and scroll through the Compound Search widget to find the best library match. These events would be repeated for every TG peak group in Claman.

**Comment by ngoccalico** [comment] 2021-06-08 18:58
@cmsand I agree. this feature will save time when analyzing a large set of data

**Comment by PMSeitzer** [comment] 2021-06-08 20:00
This is a duplicate of #413

**Comment by PMSeitzer** [comment] 2021-06-11 02:58
Completed as of ad77dc740d77f028c8606c44914ff26998170699

**Closed by PMSeitzer** 2021-06-11 02:58 UTC
Labels: enhancement
