### ISSUE TITLE
Program close immediately after trying to open a file

### ISSUE THREAD

**Issue by LivingGhost14** [eugenemel/maven#589] opened 2022-12-01 07:01 UTC
When we try to open a file program closes immediately. Also please provide a file how to install the program.

**Comment by PMSeitzer** [comment] 2022-12-01 18:05
Hi @LivingGhost14 , thanks for your report. Could you give me some more information? e.g, the version number of MAVEN, the type of file you were opening (and if you can provide the file, that would be best)?

You can install maven by downloading the installers available [here](https://github.com/eugenemel/maven/releases/latest)

**Comment by PMSeitzer** [comment] 2022-12-05 18:22
Hi @LivingGhost14, could you provide some more information?

**Comment by ChennyWestside** [comment] 2022-12-19 17:14
Hi, I'm also having this issue.

I'm using MAVEN ver 2.0.3. I'm trying to open .msML files converted from .raw. 

I'd upload a file for you, but they're all > 300 MB.

Any help would be appreciated!
Thanks,
Eric

**Comment by PMSeitzer** [comment] 2022-12-19 18:13
Hey @ChennyWestside Thanks for letting me know. Can you send me a google drive / dropbox link at phillipseitzer _at_ gmail.com with one of the files that is causing the crash? Any other information you can provide is also appreciated.

**Comment by PMSeitzer** [comment] 2023-01-24 00:02
This is a duplicate of #601 , which was fixed in `2.0.5`, at least for Windows builds.

**Closed by PMSeitzer** 2023-01-24 00:02 UTC
Labels: bug
