### ISSUE TITLE
Maven crash on MRM analysis

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#367] opened 2021-03-17 22:28 UTC
Was zooming in on the EIC pane when maven crashed. 
<img width="697" alt="Screen Shot 2021-03-17 at 3 27 33 PM" src="https://user-images.githubusercontent.com/9013133/111546769-6a37f280-8735-11eb-95db-301e053cdd5f.png">

**Comment by cmsand** [comment] 2021-03-18 00:01
Happened again. This time it was definitely during manual integration, so may have been mistaken before when I said I was zooming. 

![Screen Shot 2021-03-17 at 4 58 34 PM](https://user-images.githubusercontent.com/9013133/111553753-3b744900-8742-11eb-8d5a-072a1972b89a.png)

**Comment by cmsand** [comment] 2021-03-18 00:42
Crash happening more frequently now. Approximately every ~10 manual integrations. Maven also not recognizing most recent save after crash.

**Comment by ngoccalico** [comment] 2021-03-19 01:03
@PMSeitzer Can you move bug #369 under this one. It is happening to me too. @cmsand, it happened more frequently to me in pos than neg data, how about yours?

**Comment by ngoccalico** [comment] 2021-03-19 01:06
@PMSeitzer @cmsand  happened to me during manual bookmarking with shift+ click

**Comment by ngoccalico** [comment] 2021-03-19 02:34
![image](https://user-images.githubusercontent.com/56043766/111723551-f07d3300-8820-11eb-9b7a-7b8391ce32b1.png)

**Comment by PMSeitzer** [comment] 2021-03-20 02:09
Releasing many changes in `8.1.27.21`, consider closing this case with milestone `8.1.27.21` if the bug can't be reproduced.

**Comment by PMSeitzer** [comment] 2021-03-22 20:44
I was finally able to reproduce this by manually bookmarking with isotopes turned on.  Previously, I had no isotopes checked (change in `settingsform.cpp`).  This appears to be necessary for the bug to trigger.
I also had "add children peak to bookmark" when the bug was observed.

**Comment by PMSeitzer** [comment] 2021-03-22 23:23
This may also be related to memory access violation-associated EIC widgets #235, #277

**Comment by PMSeitzer** [comment] 2021-03-23 18:04
Based on the data that is available, what must have happened is _alwaysDisplayGroup is a copy of some PeakGroup* that was deleted, for instance, it might be a copy of _integratedPeakGroup or _lastSelectedPeakGroup. Either way, it is a dangling pointer.

This is a general problem that will affect the entire program. In general, PeakGroup*s may be deleted / reassigned all the time, sometimes by the user, where they may delete PeakGroups either by deleting an entire TableDockWidget table of PeakGroups or by deleting a single PeakGroup* from a TableDockWidget table.

There had been some effort to switch everything to smart pointers, but smart pointers don't play nice with Qt, so this was basically abandoned.

Every time a peak group is about to be deleted, probably every major reference to a PeakGroup* should be notified and set to nullptr. This could be done manually, as per signal / slot notification systems, in the same way that the library dialog unload() calls notify others.

**Comment by PMSeitzer** [comment] 2021-03-23 18:05
[1] `EicWidget::setPeakGroup()` sets a `PeakGroup*` to `_alwaysDisplayGroup`.

[2] `MainWindow::setPeakGroup()` sets a `PeakGroup*` to `_lastSelectedPeakGroup`.

[3] `MainWindow::setPeakGroup()` is Called by `TableDockWidget::showSelectedGroup()`.  The `PeakGroup*` that is passed into this call comes from the `QTreeWidgetItem*`.

[4] `MainWindow::bookmarkPeakGroup()` calls `bookmarkedPeaks->selectGroup()`, which first calls `TableDockWidget::addPeakGroup()`, and then calls `TableDockWidget::showSelectedGroup()` via signals/slots.
A series of copies of `PeakGroup()` are made to manage all of the deletion properly.

**Comment by PMSeitzer** [comment] 2021-03-23 18:07
Considered 

make `_alwaysDisplayGroup` a copy of a PeakGroup, since this `PeakGroup` can really live inside the `EICWidget` without adverse consequences.  Left some fragments in `eicwidget.cpp` in case want to go this route in the future.

For now, leaving everything as it is, as setting `_alwaysDisplayGroup` to `nullptr` makes the bug no longer reproducible.

**Comment by PMSeitzer** [comment] 2021-03-23 18:07
Closing this for now, but leaving the `eic_widget_nullptr` flag on for help with possible future cases.

**Closed by PMSeitzer** 2021-03-23 18:07 UTC
Labels: QQQ, blocker, bug, eic_widget_nullptr, high_priority
