### ISSUE TITLE
mzFileIo warning dialog for samples that are OK

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#178] opened 2020-03-05 19:03 UTC
![image](https://user-images.githubusercontent.com/56043766/76015972-e667eb00-5ed0-11ea-8e35-1365849ea433.png)

**Comment by PMSeitzer** [comment] 2020-03-06 00:09
Unable to reproduce this on my machine.

**Comment by PMSeitzer** [comment] 2021-06-24 23:22
This hasn't been observed in a while, closing.

**Closed by PMSeitzer** 2021-06-24 23:22 UTC
Labels: bug, mysterious
