### ISSUE TITLE
Maven Crashes when clicking peakgroups table

### ISSUE THREAD

**Issue by cmsand** [eugenemel/maven#38] opened 2019-07-31 23:38 UTC
Version: 8.0.25
Dataset: X0110-M001A

What happened:
Clicking around peak groups table `rumsdb`, and it crashed.

Samples were located remotely (on network drive)

error log:
```
Start groupCount= 59
Stop groupCount= 51
	groupPeaks() msec= 390
	computeEICs() Done.
 EicWidget::replot(PeakGroup* group ) group= 0x7f84c0004890
 EicWidget::setFocusLine(float rt)
addMS2Events()  found= 582
SpectraWidget::setScan(scan) 
MassCalcWidget::setPeakGroup(PeakGroup* grp)
Maven(5434,0x11251f5c0) malloc: Incorrect checksum for freed object 0x7f83e69ba220: probably modified after being freed.
Corrupt value: 0x6000000090c83ed1
Maven(5434,0x11251f5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by PMSeitzer** [comment] 2019-08-01 20:16
This is a duplicate of Issue #35

**Closed by PMSeitzer** 2019-08-01 20:16 UTC
Labels: bug, duplicate
