### ISSUE TITLE
Maven crashed then lost the "rumDB" and "peak detector" tabs

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#326] opened 2021-01-04 18:05 UTC
I loaded an older file mzrollDB using Maven 8.1.27.14. After loading everything with additional libraries, the file crashed. After that, When I tried to load the file again it loaded all of the mzML and their order, but the info od rumDB, peak detector were gone, and the bookmarks are blank. Moreover, the new Maven cannot open any copied mzrollDB files.

**Comment by ngoccalico** [comment] 2021-01-04 18:07
The crashed mzrollDB file was uploaded under the folder "Maven issue #326", and all of the mzML files can be found under metadata folder, under "X0141-M004A". Thanks!

**Comment by PMSeitzer** [comment] 2021-01-04 19:10
The file `X0141-M004A_CircadianMousePlasma.mzrollDB`, as available in this folder: https://drive.google.com/drive/u/0/folders/1b78Kpm1HHRLuKitJVisW1yougeSO8sh_

Does not contain `peakgroups` or `peaks` tables. The program shouldn't crash, but this file is probably not formatted correctly.

**Comment by PMSeitzer** [comment] 2021-01-04 23:07
From @ngoccalico:

>I loaded the file, loaded libraries, then check on a few IDs, then it crashed.

The file after the crash does not contain the `peaks` or `peakgroups` tables

**Comment by PMSeitzer** [comment] 2021-01-06 01:08
Hey @ngoccalico, I was unable to reproduce the bug when I analyzed the data.  I would recommend first deleting `20191022-Calico-Lipids-Neg` and `X0144-M004A_CircardianMousePlasma_all_compounds` from the libraries, then downloading the latest release of maven, and re-importing the aforementioned libraries, and try opening the file again.  I'd also recommend running maven with the console open, so if maven does crash, you could add the crash report to this ticket.

**Comment by PMSeitzer** [comment] 2021-01-06 23:19
Unable to reproduce issue, closing for now.

**Closed by PMSeitzer** 2021-01-06 23:19 UTC
Labels: bug, not_reproducible
