### ISSUE TITLE
rumDB library was in correct in project X0136-M004A

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#156] opened 2020-02-13 22:56 UTC
In server Z03, under the project X0136-MOO4A, please open the mzrollDB file in this folder "X0136-M004A-GPX4-lipids_mzkitchen_v2_11_output_Fri_Feb__7_11-04-49_PST_2020". I used the "X0136-M004A-GPX4-lipid_all_compounds" for the rumDB library, however, most of the matching in the loaded library didn't match the rumsDB library. I couldn't use the inseted library as much as I did with the previous project (X0135).

**Comment by PMSeitzer** [comment] 2020-02-14 22:16
This was fixed in `8.0.21`. The problem was incorrect ID mapping between matches and peak group IDs, caused by adding peak groups to the bookmarks table.

**Comment by PMSeitzer** [comment] 2020-02-14 22:17
It's worth mentioning that opening a file in a version of maven before `8.0.21` and saving the file that version will cause the group ids to be off, and the file cannot be rescued.

**Closed** 2020-02-14 22:17 UTC
Labels: bug
