### ISSUE TITLE
Maven crashing when processing Sciex QQQ data

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#369] opened 2021-03-19 01:00 UTC
```
EicWidget::integrateRegion() _alwaysDisplayGroup= 0x7febe3a171a8 _selectedGroup= 0x7febb3011590
Maven(99165,0x11c2fbdc0) malloc: can't allocate region
:*** mach_vm_map(size=601935283118080, flags: 100) failed (error code=3)
Maven(99165,0x11c2fbdc0) malloc: *** set a breakpoint in malloc_error_break to debug
libc++abi.dylib: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by PMSeitzer** [comment] 2021-03-19 02:36
This is a duplicate of #367

**Closed by PMSeitzer** 2021-03-19 02:36 UTC
Labels: QQQ, duplicate
